name: CI/CD for project

on:
  push:
    branches: [main]

env:
  PROJECT_ID: uptimeguard-495411
  REGION: europe-central2
  REPOSITORY: uptime-guard-repo
  IMAGE: uptimeimg

jobs:
  Ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Linter
        run: ruff check . --output-format=github

      - name : Run Ruff Formatter
        run: ruff format --check .

  Docker:
    runs-on: ubuntu-latest
    needs: Ruff
    env:
      PROJECT_ID: uptimeguard-495411
      REGION: europe-central2
      REPOSITORY: uptime-guard-repo
      IMAGE_NAME: uptimeimg

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME"
          docker build -t $IMAGE:${{ github.sha }} .
      
      - name: Push Docker image
        run: |
          IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME"
          docker push $IMAGE:${{ github.sha }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Docker

    steps:
      - name: Setup SSH
        run: |
          set -x

          mkdir -p ~/.ssh

          cat << 'EOF' > ~/.ssh/id_ed25519
          ${{ secrets.SSH_PRIVAT_KEY }}
          EOF

          chmod 600 ~/.ssh/id_ed25519

          ls -la ~/.ssh

          ssh-keyscan -H ${{ secrets.VM_IP }}

          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

          cat ~/.ssh/known_hosts
          whoami
          pwd
          

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}
          set -e
          cd /home/xrems/UptimeGuard

          export IMAGE=europe-central2-docker.pkg.dev/uptimeguard-495411/uptime-guard-repo/uptimeimg:${{ github.sha }}

          docker compose --env-file .env pull
          docker compose --env-file .env up -d --remove-orphans

          docker image prune -f
