name: CI for project

on:
  push:
    branches: [main]
  
jobs:
  Ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Linter
        run: ruff check . --output-format=github

      - name : Run Ruff Formatter
        run: ruff format --check .

  Docker:
    runs-on: ubuntu-latest
    needs: Ruff
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t uptimeguard:latest .

